server:
  port: 10620
  servlet:
    context-path: /

spring:
  application:
    name: rabbitmq-study-product
  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
    addresses: 127.0.0.1:5672
    virtual-host: xiaolinzi
    username: xiaolinzi
    password: xiaolinzi
    #超时时间
    connection-timeout: 10000s
    #开启消息确认模式
    publisher-confirms: true
    #开启消息可达监听
    publisher-returns: true
    #开启不可达消息不会被broker给删除
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 1 # 最小并发数
        max-concurrency: 2 # 最大并发数
        prefetch: 5 #一个请求能处理多少个消息
        default-requeue-rejected: false #意思是，消息被拒后（即未消费），重新（true）放入队列
        acknowledge-mode: auto # 自动应答
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 25 #最大重试次数
          initial-interval: 1000ms #重试间隔时间
          multiplier: 2 # 尝试，每次重试时间加倍
          max-interval: 43200000ms # 最大12小时重试

