server:
  port: 10621
  servlet:
    context-path: /

spring:
  application:
    name: rabbitmq-study-consume

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: xiaolinzi
    username: xiaolinzi
    password: xiaolinzi
#    手动签收
    listener:
      simple:
        acknowledge-mode: manual